// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;

namespace GYM.EF.Models;

public partial class AspNetUsers: IdentityUser<Guid>
{
    public virtual ICollection<AspNetUserClaims> AspNetUserClaims { get; set; } = new List<AspNetUserClaims>();

    public virtual ICollection<AspNetUserLogins> AspNetUserLogins { get; set; } = new List<AspNetUserLogins>();

    public virtual ICollection<AspNetUserTokens> AspNetUserTokens { get; set; } = new List<AspNetUserTokens>();

    public virtual ICollection<Attendance> Attendance { get; set; } = new List<Attendance>();

    public virtual ICollection<AuditLogs> AuditLogs { get; set; } = new List<AuditLogs>();

    public virtual ICollection<DiscussionMessages> DiscussionMessages { get; set; } = new List<DiscussionMessages>();

    public virtual ICollection<Discussions> Discussions { get; set; } = new List<Discussions>();

    public virtual ICollection<ExternalProviders> ExternalProviders { get; set; } = new List<ExternalProviders>();

    public virtual ICollection<Feedbacks> Feedbacks { get; set; } = new List<Feedbacks>();

    public virtual ICollection<Members> Members { get; set; } = new List<Members>();

    public virtual ICollection<Notifications> Notifications { get; set; } = new List<Notifications>();

    public virtual ICollection<Trainers> Trainers { get; set; } = new List<Trainers>();

    public virtual ICollection<WorkoutPlans> WorkoutPlans { get; set; } = new List<WorkoutPlans>();

    public virtual ICollection<AspNetRoles> Role { get; set; } = new List<AspNetRoles>();
}