// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GYM.EF.Models;

public partial class AttendanceType
{
    public int AttendanceTypeId { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Attendance> Attendances { get; set; } = new List<Attendance>();
}