// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GYM.EF.Models;

public partial class Attendance
{
    public long AttendanceId { get; set; }

    public Guid GymId { get; set; }

    public Guid UserId { get; set; }

    public int AttendanceTypeId { get; set; }

    public int SourceId { get; set; }

    public DateTime CheckinAt { get; set; }

    public DateTime? CheckoutAt { get; set; }

    public string Metadata { get; set; }

    public virtual AttendanceType AttendanceType { get; set; }

    public virtual Gym Gym { get; set; }

    public virtual AttendanceSource Source { get; set; }

    public virtual AspNetUser User { get; set; }
}