// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GYM.EF.Models;

public partial class BodyMetric
{
    public long BodyMetricId { get; set; }

    public Guid MemberId { get; set; }

    public int MetricTypeId { get; set; }

    public decimal Value { get; set; }

    public string Unit { get; set; }

    public DateTime MeasuredAt { get; set; }

    public int SourceId { get; set; }

    public virtual Member Member { get; set; }

    public virtual BodyMetricType MetricType { get; set; }

    public virtual BodyMetricSource Source { get; set; }
}