// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GYM.EF.Models;

public partial class BodyMetricSource
{
    public int SourceId { get; set; }

    public string Name { get; set; }

    public virtual ICollection<BodyMetric> BodyMetrics { get; set; } = new List<BodyMetric>();
}