// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GYM.EF.Models;

public partial class Class
{
    public Guid ClassId { get; set; }

    public Guid GymId { get; set; }

    public Guid? TrainerId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public int Capacity { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<ClassSchedule> ClassSchedules { get; set; } = new List<ClassSchedule>();

    public virtual Gym Gym { get; set; }

    public virtual Trainer Trainer { get; set; }
}