// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GYM.EF.Models;

public partial class ClassSchedules
{
    public Guid ClassScheduleId { get; set; }

    public Guid ClassId { get; set; }

    public DateTime StartAt { get; set; }

    public DateTime EndAt { get; set; }

    public string Location { get; set; }

    public virtual Classes Class { get; set; }

    public virtual ICollection<ClassBookings> ClassBookings { get; set; } = new List<ClassBookings>();
}