// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GYM.EF.Models;

public partial class Discussion
{
    public Guid DiscussionId { get; set; }

    public string Title { get; set; }

    public string Body { get; set; }

    public Guid CreatedByUserId { get; set; }

    public Guid? GymId { get; set; }

    public bool IsFranchiseWide { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual AspNetUser CreatedByUser { get; set; }

    public virtual ICollection<DiscussionMessage> DiscussionMessages { get; set; } = new List<DiscussionMessage>();

    public virtual Gym Gym { get; set; }
}