// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GYM.EF.Models;

public partial class DiscussionMessage
{
    public Guid MessageId { get; set; }

    public Guid DiscussionId { get; set; }

    public Guid FromUserId { get; set; }

    public string Message { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Discussion Discussion { get; set; }

    public virtual AspNetUser FromUser { get; set; }
}