// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GYM.EF.Models;

public partial class Exercise
{
    public Guid ExerciseId { get; set; }

    public Guid GymId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int MuscleGroupId { get; set; }

    public string Equipment { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Gym Gym { get; set; }

    public virtual MuscleGroup MuscleGroup { get; set; }

    public virtual ICollection<WorkoutDayExercise> WorkoutDayExercises { get; set; } = new List<WorkoutDayExercise>();
}