// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GYM.EF.Models;

public partial class Feedback
{
    public Guid FeedbackId { get; set; }

    public Guid FromUserId { get; set; }

    public Guid? ForTrainerId { get; set; }

    public Guid? GymId { get; set; }

    public int? Rating { get; set; }

    public string Comment { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Trainer ForTrainer { get; set; }

    public virtual AspNetUser FromUser { get; set; }

    public virtual Gym Gym { get; set; }
}