// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GYM.EF.Models;

public partial class Invoice
{
    public Guid InvoiceId { get; set; }

    public Guid SubscriptionId { get; set; }

    public Guid MemberId { get; set; }

    public Guid GymId { get; set; }

    public decimal Amount { get; set; }

    public string Currency { get; set; }

    public DateTime IssuedAt { get; set; }

    public DateTime? PaidAt { get; set; }

    public int StatusId { get; set; }

    public virtual Gym Gym { get; set; }

    public virtual Member Member { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual InvoiceStatus Status { get; set; }

    public virtual Subscription Subscription { get; set; }
}