// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GYM.EF.Models;

public partial class MembershipPlans
{
    public Guid PlanId { get; set; }

    public Guid GymId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public decimal Price { get; set; }

    public string BillingCycle { get; set; }

    public int? DurationDays { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Gyms Gym { get; set; }

    public virtual ICollection<Subscriptions> Subscriptions { get; set; } = new List<Subscriptions>();
}