// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace GYM.EF.Models;

public partial class MuscleUpGYMContext : IdentityDbContext<IdentityUser>
{
    public MuscleUpGYMContext(DbContextOptions<MuscleUpGYMContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AspNetRoleClaims> AspNetRoleClaims { get; set; }

    public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }

    public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }

    public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }

    public virtual DbSet<AspNetUserTokens> AspNetUserTokens { get; set; }

    public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }

    public virtual DbSet<Attendance> Attendance { get; set; }

    public virtual DbSet<AttendanceSources> AttendanceSources { get; set; }

    public virtual DbSet<AttendanceTypes> AttendanceTypes { get; set; }

    public virtual DbSet<AuditLogs> AuditLogs { get; set; }

    public virtual DbSet<BodyMetricSources> BodyMetricSources { get; set; }

    public virtual DbSet<BodyMetricTypes> BodyMetricTypes { get; set; }

    public virtual DbSet<BodyMetrics> BodyMetrics { get; set; }

    public virtual DbSet<ClassBookingStatuses> ClassBookingStatuses { get; set; }

    public virtual DbSet<ClassBookings> ClassBookings { get; set; }

    public virtual DbSet<ClassSchedules> ClassSchedules { get; set; }

    public virtual DbSet<Classes> Classes { get; set; }

    public virtual DbSet<DiscussionMessages> DiscussionMessages { get; set; }

    public virtual DbSet<Discussions> Discussions { get; set; }

    public virtual DbSet<Exercises> Exercises { get; set; }

    public virtual DbSet<ExternalProviders> ExternalProviders { get; set; }

    public virtual DbSet<Feedbacks> Feedbacks { get; set; }

    public virtual DbSet<Gyms> Gyms { get; set; }

    public virtual DbSet<InvoiceStatuses> InvoiceStatuses { get; set; }

    public virtual DbSet<Invoices> Invoices { get; set; }

    public virtual DbSet<Leagues> Leagues { get; set; }

    public virtual DbSet<Members> Members { get; set; }

    public virtual DbSet<MembershipPlans> MembershipPlans { get; set; }

    public virtual DbSet<MuscleGroups> MuscleGroups { get; set; }

    public virtual DbSet<NotificationStatuses> NotificationStatuses { get; set; }

    public virtual DbSet<Notifications> Notifications { get; set; }

    public virtual DbSet<Payments> Payments { get; set; }

    public virtual DbSet<SessionLogs> SessionLogs { get; set; }

    public virtual DbSet<SubscriptionStatuses> SubscriptionStatuses { get; set; }

    public virtual DbSet<Subscriptions> Subscriptions { get; set; }

    public virtual DbSet<Trainers> Trainers { get; set; }

    public virtual DbSet<WorkoutDayExercises> WorkoutDayExercises { get; set; }

    public virtual DbSet<WorkoutDayTypes> WorkoutDayTypes { get; set; }

    public virtual DbSet<WorkoutDays> WorkoutDays { get; set; }

    public virtual DbSet<WorkoutPlans> WorkoutPlans { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AspNetRoleClaims>(entity =>
        {
            entity.HasOne(d => d.Role).WithMany(p => p.AspNetRoleClaims)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AspNetRoleClaims_Role");
        });

        modelBuilder.Entity<AspNetRoles>(entity =>
        {
            entity.Property(e => e.Id).HasDefaultValueSql("(newsequentialid())");
            entity.Property(e => e.Name).HasMaxLength(256);
            entity.Property(e => e.NormalizedName).HasMaxLength(256);
        });

        modelBuilder.Entity<AspNetUserClaims>(entity =>
        {
            entity.HasOne(d => d.User).WithMany(p => p.AspNetUserClaims)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AspNetUserClaims_User");
        });

        modelBuilder.Entity<AspNetUserLogins>(entity =>
        {
            entity.HasKey(e => new { e.LoginProvider, e.ProviderKey });

            entity.Property(e => e.LoginProvider).HasMaxLength(128);
            entity.Property(e => e.ProviderKey).HasMaxLength(128);
            entity.Property(e => e.ProviderDisplayName).HasMaxLength(256);

            entity.HasOne(d => d.User).WithMany(p => p.AspNetUserLogins)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AspNetUserLogins_User");
        });

        modelBuilder.Entity<AspNetUserTokens>(entity =>
        {
            entity.HasKey(e => new { e.UserId, e.LoginProvider, e.Name });

            entity.Property(e => e.LoginProvider).HasMaxLength(128);
            entity.Property(e => e.Name).HasMaxLength(128);

            entity.HasOne(d => d.User).WithMany(p => p.AspNetUserTokens)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AspNetUserTokens_User");
        });

        modelBuilder.Entity<AspNetUsers>(entity =>
        {
            entity.Property(e => e.Id).HasDefaultValueSql("(newsequentialid())");
            entity.Property(e => e.Email).HasMaxLength(256);
            entity.Property(e => e.NormalizedEmail).HasMaxLength(256);
            entity.Property(e => e.NormalizedUserName).HasMaxLength(256);
            entity.Property(e => e.PhoneNumber).HasMaxLength(50);
            entity.Property(e => e.UserName).HasMaxLength(256);

            entity.HasMany(d => d.Role).WithMany(p => p.User)
                .UsingEntity<Dictionary<string, object>>(
                    "AspNetUserRoles",
                    r => r.HasOne<AspNetRoles>().WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_AspNetUserRoles_Role"),
                    l => l.HasOne<AspNetUsers>().WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_AspNetUserRoles_User"),
                    j =>
                    {
                        j.HasKey("UserId", "RoleId");
                    });
        });

        modelBuilder.Entity<Attendance>(entity =>
        {
            entity.Property(e => e.CheckinAt).HasPrecision(3);
            entity.Property(e => e.CheckoutAt).HasPrecision(3);

            entity.HasOne(d => d.AttendanceType).WithMany(p => p.Attendance)
                .HasForeignKey(d => d.AttendanceTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Attendance_AttendanceTypes");

            entity.HasOne(d => d.Gym).WithMany(p => p.Attendance)
                .HasForeignKey(d => d.GymId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Attendance_Gyms");

            entity.HasOne(d => d.Source).WithMany(p => p.Attendance)
                .HasForeignKey(d => d.SourceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Attendance_AttendanceSources");

            entity.HasOne(d => d.User).WithMany(p => p.Attendance)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Attendance_AspNetUsers");
        });

        modelBuilder.Entity<AttendanceSources>(entity =>
        {
            entity.HasKey(e => e.SourceId);

            entity.Property(e => e.SourceId).ValueGeneratedNever();
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<AttendanceTypes>(entity =>
        {
            entity.HasKey(e => e.AttendanceTypeId);

            entity.Property(e => e.AttendanceTypeId).ValueGeneratedNever();
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<AuditLogs>(entity =>
        {
            entity.HasKey(e => e.AuditId);

            entity.Property(e => e.Action)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.CreatedAt).HasPrecision(3);
            entity.Property(e => e.Entity).HasMaxLength(200);
            entity.Property(e => e.EntityId).HasMaxLength(200);

            entity.HasOne(d => d.User).WithMany(p => p.AuditLogs)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_AuditLogs_AspNetUsers");
        });

        modelBuilder.Entity<BodyMetricSources>(entity =>
        {
            entity.HasKey(e => e.SourceId);

            entity.Property(e => e.SourceId).ValueGeneratedNever();
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<BodyMetricTypes>(entity =>
        {
            entity.HasKey(e => e.MetricTypeId);

            entity.Property(e => e.MetricTypeId).ValueGeneratedNever();
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<BodyMetrics>(entity =>
        {
            entity.HasKey(e => e.BodyMetricId);

            entity.Property(e => e.MeasuredAt).HasPrecision(3);
            entity.Property(e => e.Unit).HasMaxLength(20);
            entity.Property(e => e.Value).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.Member).WithMany(p => p.BodyMetrics)
                .HasForeignKey(d => d.MemberId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BodyMetrics_Members");

            entity.HasOne(d => d.MetricType).WithMany(p => p.BodyMetrics)
                .HasForeignKey(d => d.MetricTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BodyMetrics_BodyMetricTypes");

            entity.HasOne(d => d.Source).WithMany(p => p.BodyMetrics)
                .HasForeignKey(d => d.SourceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BodyMetrics_BodyMetricSources");
        });

        modelBuilder.Entity<ClassBookingStatuses>(entity =>
        {
            entity.HasKey(e => e.StatusId);

            entity.Property(e => e.StatusId).ValueGeneratedNever();
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<ClassBookings>(entity =>
        {
            entity.HasKey(e => e.ClassBookingId);

            entity.Property(e => e.ClassBookingId).HasDefaultValueSql("(newsequentialid())");
            entity.Property(e => e.BookedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.CancelledAt).HasPrecision(3);

            entity.HasOne(d => d.ClassSchedule).WithMany(p => p.ClassBookings)
                .HasForeignKey(d => d.ClassScheduleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ClassBookings_ClassSchedules");

            entity.HasOne(d => d.Member).WithMany(p => p.ClassBookings)
                .HasForeignKey(d => d.MemberId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ClassBookings_Members");

            entity.HasOne(d => d.Status).WithMany(p => p.ClassBookings)
                .HasForeignKey(d => d.StatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ClassBookings_ClassBookingStatuses");
        });

        modelBuilder.Entity<ClassSchedules>(entity =>
        {
            entity.HasKey(e => e.ClassScheduleId);

            entity.Property(e => e.ClassScheduleId).HasDefaultValueSql("(newsequentialid())");
            entity.Property(e => e.EndAt).HasPrecision(3);
            entity.Property(e => e.Location).HasMaxLength(200);
            entity.Property(e => e.StartAt).HasPrecision(3);

            entity.HasOne(d => d.Class).WithMany(p => p.ClassSchedules)
                .HasForeignKey(d => d.ClassId)
                .HasConstraintName("FK_ClassSchedules_Classes");
        });

        modelBuilder.Entity<Classes>(entity =>
        {
            entity.HasKey(e => e.ClassId);

            entity.Property(e => e.ClassId).HasDefaultValueSql("(newsequentialid())");
            entity.Property(e => e.Capacity).HasDefaultValue(20);
            entity.Property(e => e.CreatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(200);

            entity.HasOne(d => d.Gym).WithMany(p => p.Classes)
                .HasForeignKey(d => d.GymId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Classes_Gyms");

            entity.HasOne(d => d.Trainer).WithMany(p => p.Classes)
                .HasForeignKey(d => d.TrainerId)
                .HasConstraintName("FK_Classes_Trainers");
        });

        modelBuilder.Entity<DiscussionMessages>(entity =>
        {
            entity.HasKey(e => e.MessageId);

            entity.Property(e => e.MessageId).HasDefaultValueSql("(newsequentialid())");
            entity.Property(e => e.CreatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Message).IsRequired();

            entity.HasOne(d => d.Discussion).WithMany(p => p.DiscussionMessages)
                .HasForeignKey(d => d.DiscussionId)
                .HasConstraintName("FK_DiscussionMessages_Discussions");

            entity.HasOne(d => d.FromUser).WithMany(p => p.DiscussionMessages)
                .HasForeignKey(d => d.FromUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DiscussionMessages_AspNetUsers");
        });

        modelBuilder.Entity<Discussions>(entity =>
        {
            entity.HasKey(e => e.DiscussionId);

            entity.Property(e => e.DiscussionId).HasDefaultValueSql("(newsequentialid())");
            entity.Property(e => e.CreatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(300);

            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.Discussions)
                .HasForeignKey(d => d.CreatedByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Discussions_AspNetUsers");

            entity.HasOne(d => d.Gym).WithMany(p => p.Discussions)
                .HasForeignKey(d => d.GymId)
                .HasConstraintName("FK_Discussions_Gyms");
        });

        modelBuilder.Entity<Exercises>(entity =>
        {
            entity.HasKey(e => e.ExerciseId);

            entity.Property(e => e.ExerciseId).HasDefaultValueSql("(newsequentialid())");
            entity.Property(e => e.CreatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Equipment).HasMaxLength(200);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);

            entity.HasOne(d => d.Gym).WithMany(p => p.Exercises)
                .HasForeignKey(d => d.GymId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Exercises_Gyms");

            entity.HasOne(d => d.MuscleGroup).WithMany(p => p.Exercises)
                .HasForeignKey(d => d.MuscleGroupId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Exercises_MuscleGroups");
        });

        modelBuilder.Entity<ExternalProviders>(entity =>
        {
            entity.HasKey(e => e.ProviderId);

            entity.Property(e => e.ProviderId).HasDefaultValueSql("(newsequentialid())");
            entity.Property(e => e.CreatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.ExpiresAt).HasPrecision(3);
            entity.Property(e => e.ExternalUserId).HasMaxLength(200);
            entity.Property(e => e.LastSyncAt).HasPrecision(3);
            entity.Property(e => e.ProviderName)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.User).WithMany(p => p.ExternalProviders)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_ExternalProviders_AspNetUsers");
        });

        modelBuilder.Entity<Feedbacks>(entity =>
        {
            entity.HasKey(e => e.FeedbackId);

            entity.Property(e => e.FeedbackId).HasDefaultValueSql("(newsequentialid())");
            entity.Property(e => e.CreatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");

            entity.HasOne(d => d.ForTrainer).WithMany(p => p.Feedbacks)
                .HasForeignKey(d => d.ForTrainerId)
                .HasConstraintName("FK_Feedbacks_Trainers");

            entity.HasOne(d => d.FromUser).WithMany(p => p.Feedbacks)
                .HasForeignKey(d => d.FromUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Feedbacks_AspNetUsers");

            entity.HasOne(d => d.Gym).WithMany(p => p.Feedbacks)
                .HasForeignKey(d => d.GymId)
                .HasConstraintName("FK_Feedbacks_Gyms");
        });

        modelBuilder.Entity<Gyms>(entity =>
        {
            entity.HasKey(e => e.GymId);

            entity.Property(e => e.GymId).HasDefaultValueSql("(newsequentialid())");
            entity.Property(e => e.CreatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.Timezone).HasMaxLength(64);
        });

        modelBuilder.Entity<InvoiceStatuses>(entity =>
        {
            entity.HasKey(e => e.StatusId);

            entity.Property(e => e.StatusId).ValueGeneratedNever();
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Invoices>(entity =>
        {
            entity.HasKey(e => e.InvoiceId);

            entity.Property(e => e.InvoiceId).HasDefaultValueSql("(newsequentialid())");
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Currency)
                .IsRequired()
                .HasMaxLength(10)
                .HasDefaultValue("USD");
            entity.Property(e => e.IssuedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.PaidAt).HasPrecision(3);

            entity.HasOne(d => d.Gym).WithMany(p => p.Invoices)
                .HasForeignKey(d => d.GymId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Invoices_Gyms");

            entity.HasOne(d => d.Member).WithMany(p => p.Invoices)
                .HasForeignKey(d => d.MemberId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Invoices_Members");

            entity.HasOne(d => d.Status).WithMany(p => p.Invoices)
                .HasForeignKey(d => d.StatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Invoices_InvoiceStatuses");

            entity.HasOne(d => d.Subscription).WithMany(p => p.Invoices)
                .HasForeignKey(d => d.SubscriptionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Invoices_Subscriptions");
        });

        modelBuilder.Entity<Leagues>(entity =>
        {
            entity.HasKey(e => e.LeagueId);

            entity.Property(e => e.LeagueId).ValueGeneratedNever();
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Members>(entity =>
        {
            entity.HasKey(e => e.MemberId);

            entity.Property(e => e.MemberId).HasDefaultValueSql("(newsequentialid())");
            entity.Property(e => e.CreatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Gender).HasMaxLength(20);
            entity.Property(e => e.JoinDate).HasDefaultValueSql("(CONVERT([date],sysutcdatetime()))");

            entity.HasOne(d => d.Gym).WithMany(p => p.Members)
                .HasForeignKey(d => d.GymId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Members_Gyms");

            entity.HasOne(d => d.League).WithMany(p => p.Members)
                .HasForeignKey(d => d.LeagueId)
                .HasConstraintName("FK_Members_Leagues");

            entity.HasOne(d => d.User).WithMany(p => p.Members)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Members_AspNetUsers");
        });

        modelBuilder.Entity<MembershipPlans>(entity =>
        {
            entity.HasKey(e => e.PlanId);

            entity.Property(e => e.PlanId).HasDefaultValueSql("(newsequentialid())");
            entity.Property(e => e.BillingCycle)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Description).HasMaxLength(1000);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Gym).WithMany(p => p.MembershipPlans)
                .HasForeignKey(d => d.GymId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MembershipPlans_Gyms");
        });

        modelBuilder.Entity<MuscleGroups>(entity =>
        {
            entity.HasKey(e => e.MuscleGroupId);

            entity.Property(e => e.MuscleGroupId).ValueGeneratedNever();
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<NotificationStatuses>(entity =>
        {
            entity.HasKey(e => e.StatusId);

            entity.Property(e => e.StatusId).ValueGeneratedNever();
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Notifications>(entity =>
        {
            entity.HasKey(e => e.NotificationId);

            entity.Property(e => e.Channel)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.SentAt).HasPrecision(3);
            entity.Property(e => e.TemplateKey)
                .IsRequired()
                .HasMaxLength(200);

            entity.HasOne(d => d.Gym).WithMany(p => p.Notifications)
                .HasForeignKey(d => d.GymId)
                .HasConstraintName("FK_Notifications_Gyms");

            entity.HasOne(d => d.Status).WithMany(p => p.Notifications)
                .HasForeignKey(d => d.StatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Notifications_NotificationStatuses");

            entity.HasOne(d => d.ToUser).WithMany(p => p.Notifications)
                .HasForeignKey(d => d.ToUserId)
                .HasConstraintName("FK_Notifications_AspNetUsers");
        });

        modelBuilder.Entity<Payments>(entity =>
        {
            entity.HasKey(e => e.PaymentId);

            entity.Property(e => e.PaymentId).HasDefaultValueSql("(newsequentialid())");
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Method)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.PaidAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.ProviderTransactionId).HasMaxLength(200);

            entity.HasOne(d => d.Gym).WithMany(p => p.Payments)
                .HasForeignKey(d => d.GymId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Payments_Gyms");

            entity.HasOne(d => d.Invoice).WithMany(p => p.Payments)
                .HasForeignKey(d => d.InvoiceId)
                .HasConstraintName("FK_Payments_Invoices");

            entity.HasOne(d => d.Member).WithMany(p => p.Payments)
                .HasForeignKey(d => d.MemberId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Payments_Members");
        });

        modelBuilder.Entity<SessionLogs>(entity =>
        {
            entity.HasKey(e => e.SessionLogId);

            entity.Property(e => e.SessionLogId).HasDefaultValueSql("(newsequentialid())");
            entity.Property(e => e.PerformedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");

            entity.HasOne(d => d.Member).WithMany(p => p.SessionLogs)
                .HasForeignKey(d => d.MemberId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SessionLogs_Members");

            entity.HasOne(d => d.Trainer).WithMany(p => p.SessionLogs)
                .HasForeignKey(d => d.TrainerId)
                .HasConstraintName("FK_SessionLogs_Trainers");

            entity.HasOne(d => d.WorkoutPlan).WithMany(p => p.SessionLogs)
                .HasForeignKey(d => d.WorkoutPlanId)
                .HasConstraintName("FK_SessionLogs_WorkoutPlans");
        });

        modelBuilder.Entity<SubscriptionStatuses>(entity =>
        {
            entity.HasKey(e => e.StatusId);

            entity.Property(e => e.StatusId).ValueGeneratedNever();
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Subscriptions>(entity =>
        {
            entity.HasKey(e => e.SubscriptionId);

            entity.Property(e => e.SubscriptionId).HasDefaultValueSql("(newsequentialid())");
            entity.Property(e => e.AutoRenew).HasDefaultValue(true);
            entity.Property(e => e.CreatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");

            entity.HasOne(d => d.Member).WithMany(p => p.Subscriptions)
                .HasForeignKey(d => d.MemberId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Subscriptions_Members");

            entity.HasOne(d => d.Plan).WithMany(p => p.Subscriptions)
                .HasForeignKey(d => d.PlanId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Subscriptions_MembershipPlans");

            entity.HasOne(d => d.Status).WithMany(p => p.Subscriptions)
                .HasForeignKey(d => d.StatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Subscriptions_SubscriptionStatuses");
        });

        modelBuilder.Entity<Trainers>(entity =>
        {
            entity.HasKey(e => e.TrainerId);

            entity.Property(e => e.TrainerId).HasDefaultValueSql("(newsequentialid())");
            entity.Property(e => e.CreatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.IsAvailable).HasDefaultValue(true);

            entity.HasOne(d => d.Gym).WithMany(p => p.Trainers)
                .HasForeignKey(d => d.GymId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Trainers_Gyms");

            entity.HasOne(d => d.User).WithMany(p => p.Trainers)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_Trainers_AspNetUsers");
        });

        modelBuilder.Entity<WorkoutDayExercises>(entity =>
        {
            entity.Property(e => e.Id).HasDefaultValueSql("(newsequentialid())");
            entity.Property(e => e.Reps).HasMaxLength(50);

            entity.HasOne(d => d.Exercise).WithMany(p => p.WorkoutDayExercises)
                .HasForeignKey(d => d.ExerciseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_WorkoutDayExercises_Exercises");

            entity.HasOne(d => d.WorkoutDay).WithMany(p => p.WorkoutDayExercises)
                .HasForeignKey(d => d.WorkoutDayId)
                .HasConstraintName("FK_WorkoutDayExercises_WorkoutDays");
        });

        modelBuilder.Entity<WorkoutDayTypes>(entity =>
        {
            entity.HasKey(e => e.DayTypeId);

            entity.Property(e => e.DayTypeId).ValueGeneratedNever();
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<WorkoutDays>(entity =>
        {
            entity.HasKey(e => e.WorkoutDayId);

            entity.Property(e => e.WorkoutDayId).HasDefaultValueSql("(newsequentialid())");
            entity.Property(e => e.DayType).HasMaxLength(100);

            entity.HasOne(d => d.WorkoutPlan).WithMany(p => p.WorkoutDays)
                .HasForeignKey(d => d.WorkoutPlanId)
                .HasConstraintName("FK_WorkoutDays_WorkoutPlans");
        });

        modelBuilder.Entity<WorkoutPlans>(entity =>
        {
            entity.HasKey(e => e.WorkoutPlanId);

            entity.Property(e => e.WorkoutPlanId).HasDefaultValueSql("(newsequentialid())");
            entity.Property(e => e.CreatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);

            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.WorkoutPlans)
                .HasForeignKey(d => d.CreatedByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_WorkoutPlans_AspNetUsers");

            entity.HasOne(d => d.DayType).WithMany(p => p.WorkoutPlans)
                .HasForeignKey(d => d.DayTypeId)
                .HasConstraintName("FK_WorkoutPlans_WorkoutDayTypes");

            entity.HasOne(d => d.Gym).WithMany(p => p.WorkoutPlans)
                .HasForeignKey(d => d.GymId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_WorkoutPlans_Gyms");

            entity.HasOne(d => d.Member).WithMany(p => p.WorkoutPlans)
                .HasForeignKey(d => d.MemberId)
                .HasConstraintName("FK_WorkoutPlans_Members");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}