// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GYM.EF.Models;

public partial class Notifications
{
    public long NotificationId { get; set; }

    public Guid? GymId { get; set; }

    public Guid? ToUserId { get; set; }

    public string Channel { get; set; }

    public string TemplateKey { get; set; }

    public string Payload { get; set; }

    public int StatusId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? SentAt { get; set; }

    public virtual Gyms Gym { get; set; }

    public virtual NotificationStatuses Status { get; set; }

    public virtual AspNetUsers ToUser { get; set; }
}