// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GYM.EF.Models;

public partial class Payment
{
    public Guid PaymentId { get; set; }

    public Guid? InvoiceId { get; set; }

    public Guid MemberId { get; set; }

    public Guid GymId { get; set; }

    public decimal Amount { get; set; }

    public string Method { get; set; }

    public string ProviderTransactionId { get; set; }

    public DateTime PaidAt { get; set; }

    public virtual Gym Gym { get; set; }

    public virtual Invoice Invoice { get; set; }

    public virtual Member Member { get; set; }
}