// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GYM.EF.Models;

public partial class SessionLog
{
    public Guid SessionLogId { get; set; }

    public Guid? WorkoutPlanId { get; set; }

    public Guid MemberId { get; set; }

    public Guid? TrainerId { get; set; }

    public DateTime PerformedAt { get; set; }

    public string Notes { get; set; }

    public int? DurationMinutes { get; set; }

    public virtual Member Member { get; set; }

    public virtual Trainer Trainer { get; set; }

    public virtual WorkoutPlan WorkoutPlan { get; set; }
}