// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GYM.EF.Models;

public partial class SubscriptionStatuses
{
    public int StatusId { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Subscriptions> Subscriptions { get; set; } = new List<Subscriptions>();
}