// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GYM.EF.Models;

public partial class Subscription
{
    public Guid SubscriptionId { get; set; }

    public Guid MemberId { get; set; }

    public Guid PlanId { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public int StatusId { get; set; }

    public bool AutoRenew { get; set; }

    public DateTime? NextBillingDate { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<Invoice> Invoices { get; set; } = new List<Invoice>();

    public virtual Member Member { get; set; }

    public virtual MembershipPlan Plan { get; set; }

    public virtual SubscriptionStatus Status { get; set; }
}