// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GYM.EF.Models;

public partial class UserRole
{
    public Guid UserRoleId { get; set; }

    public Guid UserId { get; set; }

    public Guid RoleId { get; set; }

    public Guid? GymId { get; set; }

    public DateTime AssignedAt { get; set; }

    public virtual Role Role { get; set; }

    public virtual AspNetUser User { get; set; }
}