// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GYM.EF.Models;

public partial class WorkoutDayExercises
{
    public Guid Id { get; set; }

    public Guid WorkoutDayId { get; set; }

    public Guid ExerciseId { get; set; }

    public int? Sets { get; set; }

    public string Reps { get; set; }

    public int? OrderIndex { get; set; }

    public virtual Exercises Exercise { get; set; }

    public virtual WorkoutDays WorkoutDay { get; set; }
}