// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GYM.EF.Models;

public partial class WorkoutPlans
{
    public Guid WorkoutPlanId { get; set; }

    public Guid GymId { get; set; }

    public Guid? MemberId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public bool IsTemplate { get; set; }

    public int? DayTypeId { get; set; }

    public Guid CreatedByUserId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual AspNetUsers CreatedByUser { get; set; }

    public virtual WorkoutDayTypes DayType { get; set; }

    public virtual Gyms Gym { get; set; }

    public virtual Members Member { get; set; }

    public virtual ICollection<SessionLogs> SessionLogs { get; set; } = new List<SessionLogs>();

    public virtual ICollection<WorkoutDays> WorkoutDays { get; set; } = new List<WorkoutDays>();
}