// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GYM.EF.Models;

public partial class WorkoutDay
{
    public Guid WorkoutDayId { get; set; }

    public Guid WorkoutPlanId { get; set; }

    public int DayOrder { get; set; }

    public string DayType { get; set; }

    public virtual ICollection<WorkoutDayExercise> WorkoutDayExercises { get; set; } = new List<WorkoutDayExercise>();

    public virtual WorkoutPlan WorkoutPlan { get; set; }
}