// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GYM.EF.Models;

public partial class WorkoutPlan
{
    public Guid WorkoutPlanId { get; set; }

    public Guid GymId { get; set; }

    public Guid? MemberId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public bool IsTemplate { get; set; }

    public int? DayTypeId { get; set; }

    public Guid CreatedByUserId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual AspNetUser CreatedByUser { get; set; }

    public virtual WorkoutDayType DayType { get; set; }

    public virtual Gym Gym { get; set; }

    public virtual Member Member { get; set; }

    public virtual ICollection<SessionLog> SessionLogs { get; set; } = new List<SessionLog>();

    public virtual ICollection<WorkoutDay> WorkoutDays { get; set; } = new List<WorkoutDay>();
}